# -*- coding: utf-8 -*-
"""23November_9pm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0bwBUXsngPA6GDyGDl7kGVu8rMCqrRH
"""

name = '''su""m'it's'''

print(name)

15 /4

15 // 4

17 % 4

2345 % 2



"""# Operators

- arithematic
- comparision operators


"""

3 * 'sumit'

'sumit' + 'kumar'    #string concatenation

# int  * str
# str  + str (conacatenation)

'-' * 100



# area of rectangle
# A = L * B

L = 5
B = 10
A = L * B

print('the area of rectangle is' , A)

# area of circle
pi = 3.14      # pi is a constant
r = 3           # r is radius
a = pi * r ** 2         # area of a circle
print('area of circle is',a)         # printing the area

input()

name = input()

print(name)

# create a program asking for your name age and height
name = input('enter your name ')
age = input('enter your age ')
height = input('enter your height ')
print('my name is',name,'and my age is',age,'with a height of',height)

print(type(name))
print(type(age))
print(type(height))

L = input('Enter length ')
B = input('Enter breadth ')
A = L * B
print(A)

"""# type casting
conversion of one data type to another
"""

int('s')

int('345')

float('45.3')

str(45)

L = int(input('enter length '))
B = int(input('enter breadth '))
A = L * B
print(A)

# convert the temp_c to temp_f
# take temp_c as input in float

#(15°C × 9/5) + 32 = 59°F

temp_c = float(input('Enter the temp in celcius '))
temp_f = (temp_c * (9/5)) + 32
print('the temp in celcius is ',temp_c,'and in far is',temp_f)

'''
homework:
1. calculate the area of circle
take pi as constant value 3.14
take radius as input in float
the final area must be in integer

take any 3 shapes and calculate their areas using input function
'''

# comparision operator

'sumit' == 'sumit'

'S' == 's'

# ASCII values - 5 minute read

# for and all conditions must be True to get True result
# for or any one of the condition need rto be True
# atleast one True for or to get True result